[colors.primary]
background = "#eeeeee"
foreground = "#ffffff"

[font]
size = 15.0

[font.normal]
family = "Source Code Pro"
style = "Medium"

[shell]
args = ["--login"]
program = "/bin/fish"

[window]
opacity = 0.1

[window.padding]
x = 20
y = 20